requires = ["tox>=4"]
env_list = ["3.13", "3.12", "3.11", "3.10", "3.9"]

[env_run_base]
description = "run unit tests"
runner = "uv-venv-lock-runner"
deps = [
    "pytest>=8",
    "pytest-sugar"
]
commands = [["pytest", { replace = "posargs", default = ["test"], extend = true }]]
